package com.MotoassemblyPlant.solution.models;

import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Data;	
import lombok.NoArgsConstructor;

import org.springframework.data.annotation.Id;

@Document(collection = "Brakes")
@Data
@AllArgsConstructor
public class Brakes {
	
	@Id
    private String part_id; // The ID will be automatically generated by MongoDB
    private String part_number;
    private String assembly_status;
    private String status_timestamp;
	
}
